### PR TITLE
Removing R27 and R29 reserved registers.

### LINKED ISSUE #46: ARM64 asm uses reserved registers
## Background

In golang for arm64, the following registers are [marked as reserved](https://go.dev/doc/asm#arm64)
- R18
- R27
- R28
- R29
- R30

The registers of note here are `R27` and `R29` as they are used by the `mul` macro (expanded in `gfpMul`).

## Explanation

I'm not sure what the impact is of overwriting `R27`, but `R29` (the frame pointer) gets written to the stack when calling another function after executing the `mul` code. The go runtime assumes that it is able to traverse the stack by repeatedly dereferencing the frame pointer. Some examples of functions that traverse the stack by following the frame pointer are:

- https://github.com/golang/go/blob/go1.24.1/src/runtime/mprof.go#L574-L618
- https://github.com/golang/go/blob/go1.24.1/src/runtime/tracestack.go#L251-L263

Because the frame pointer has been clobbered, these stack traversals can segfault.

## Test

When run on arm64, the following test (added [here](https://github.com/cloudflare/bn256/blob/master/gfp_test.go#L96)) may produce a `SIGSEGV: segmentation violation`. The crash does not happen every time, as it requires lock contention inside the call to `fmt.Print("")`.
```golang
t.Run("mul_fp_corruption", func(t *testing.T) {
	// By enabling mutex profiling, the go runtime will traverse the stack
	// to measure mutex operations when a mutex is unlocked when a goroutine
	// is blocking on it.
	runtime.SetMutexProfileFraction(1)

	var wg sync.WaitGroup
	wg.Add(testTimes)
	for i := 0; i < testTimes; i++ {
		// If multiple goroutines interact with a global sync pool, the
		// goroutines may block on acquiring a lock. When that happens, the
		// mutex profiler will traverse the stack.
		go func() {
			defer wg.Done()

			a := togfP(randomGF(rand.Reader))
			b := togfP(randomGF(rand.Reader))
			c := &gfP{}

			// Corrupt the Frame Pointer.
			gfpMul(c, a, b)

			// Calling another function stores the FP on the stack.
			//
			// Additionally, Print ends up interacting with a global sync
			// pool which can cause this stack to be traversed.
			fmt.Print("")
		}()
	}
	wg.Wait()
})
```

### PR DESCRIPTION
**Pull request by armfazh**
According to Go documentation for ARM64 (https://go.dev/doc/asm#arm64)

> R18 is the "platform register", reserved on the Apple platform. To prevent accidental misuse, the register is named R18_PLATFORM. R27 and R28 are reserved by the compiler and linker. R29 is the frame pointer. R30 is the link register.

Remove R27 and R29 registers used in multiplication. No extra stack was needed.
 
Fixes #46

### CODE REVIEW

File: mul_arm64.h [hunk 1]
```diff
@@ -16,54 +16,54 @@
...
+	ADCS c6, c3 \
+	ADCS c7, c4 \
 	ADCS  ZR, c5 \
 	\
 	MUL R3, R5, R1 \
 	UMULH R3, R5, R26 \
 	MUL R3, R6, R0 \
 	ADDS R0, R26 \
-	UMULH R3, R6, R27 \
+	UMULH R3, R6, R2 \
```
Comment (StephenButtolph) [inline mul_arm64.h:41]: By modifying `R2` here - won't we modify its value in line 108 of `·gfpMul` and then use the modified value in L110 of `gfpReduce()`?

File: mul_arm64.h [hunk 2]
```diff
@@ -16,54 +16,54 @@
...
 	UMULH R4, R5, R26 \
 	MUL R4, R6, R0 \
 	ADDS R0, R26 \
-	UMULH R4, R6, R27 \
+	UMULH R4, R6, R2 \
 	MUL R4, R7, R0 \
-	ADCS R0, R27 \
-	UMULH R4, R7, R29 \
+	ADCS R0, R2 \
+	UMULH R4, R7, R3 \
```
Comment (StephenButtolph) [inline mul_arm64.h:62]: Same comment about `R3` as `R2` above

**Comment by StephenButtolph** [comment]
@armfazh Sorry to bother again 😬. Was wondering if you had any estimated timeline for this fix?

File: mul_arm64.h (hunk 1 above)
Comment (armfazh) [reply mul_arm64.h:41]: I've checked the registers that are overwritten are not used afterwards.

**Review by bwesterb — APPROVED** [review]

File: mul_arm64.h (hunk 1 above)
Comment (StephenButtolph) [reply mul_arm64.h:41]: Ah, I hadn't noticed that R1-R4 are re-initialized at the start of `gfpReduce`. Duh. Thanks for seeing this through! ❤️
